Notes 
-----
* Glossary of terms
** Recipes
- A list of individual Tasks needed to produce a Product or Service.  
** Task
- Tasks are a list of instructions for completing a specific task. The instructions include the inventory items that will be consumed, the equipment you'll use and the final product or service. 
- Each task is seperated out by the equipment used.
- A task is different than a recipe in that each individual step needs to be done in order and cannot be done concurrently by seperate individual, or at a later time.
- Tasks that don't result in a product are called services. 
*** Composed of three parts
- An ordered list of Steps to achieve a Task
- the Equipment needed, and the time required
- the Ingredient Items needed, and their Units of measure
- any intermediate Products created used in later Tasks
** Items
- Physical items in your inventory, equipment you use, and products which you produce, or purchased from a supplier are all saved as Items. 
- Items have names, descriptions and are uniquely addressable.
** Ingredients
- Ingredients are Items that are consumed by a Tasks. These can be Products from other Tasks.
** Products
- Products are Items created by a Recipe
- Products can also be known as Physical Goods
- these can be biproducts (waste) or sellable Items.
** Equipment
- Items used but not consummed by a Task
** Duration
- the time a task takes to complete using equipment
** Services
- Services are non-tangible products of tasks.
- examples: cleaning, body work, instruction, maintenance tasks
** Units
- the unit of measure needed for each item
- These can be converted when an appropriate conversion factor is saved in the system
- Units are stored in relation to SI base units
*** SI Base Units
- Meter (m) length unit of measurement:
  Distance traveled by light in a vacuum in 1/299,792,458 seconds
- Second (s) time unit of measurement:
  9,192,631,770 cycles of radiation of an atom of caesium-133
- Kilogram (kg) mass unit of measurement:
  Planck’s constant divided by 6.626,070,15 × 10−34 m−2s
- Candela (cd) luminous intensity measurement unit:
  Light source with monochromatic radiation of frequency 540 × 1012 Hz and radiant intensity of 1/683 watt per steradian
- Kelvin (K) temperature unit of measurement:
  Boltzmann constant, defined as a change in thermal energy of 1.380 649 × 10−23 joules
- Ampere (A) electric current measurement unit:
  Flow equal to 1/1.602176634×10−19 elementary charges per second
- Mole (mol) amount of substance measurement unit:
  Avogadro constant, defined as 6.02214076 ×1023 elementary entities.
** Inventory
- Items stored in a specific location for later use.
** Suppliers
- The manufacturer or seller of items that you use.
** Events
- The date, time and location used when scheduling tasks.
** Messages
- Posts, or comments linked to Tasks, Recipes, Events, etc that are used for users to coordinate their work.
** Hash Chains
- Each feed is a append only log of messages that contain a cryptographic signature, proving that the message was written by someone in possession of the feed's private key.

-----
* Datastructures & Message Schemas
- Record schemas stored as messages in SSB.  
- As messages each has a timestamp, author and unique key not shown
- possible fields to be added later indicated with question mark (?)
*** Item
- name
- description
? density (g/cm^3)
? specs (nutrition, dimensions, sizes, color, etc.)
? wikipedia category
*** Unit
- name
- type [distance, volume or weight]
*** Unit_Conversion
- unit1
- unit2
- conversion_factor
*** Recipe
- name
- description
- tags
? notes
? reference    //citation to previous work or versions from which this is adapted
- task_list  
**** Calculateable from task_list:
+ equipment_list
+ total_time
+ item_list (qty, unit, item)
+ instruction_list
+ media_list

Example:

Rib Eye with Cherry Mustard Marmalead and Porcini
Adapted from Alain Ducasse
Yiels: four .25 kg portions

| INGREDIENTS                     | QUANTITY | SCALING | PROCEDURE                                        |
|---------------------------------+----------+---------+--------------------------------------------------|
| Beef rib eye, bone in 5cm       | 800g     |    100% | 1. Vacuum seal together                          |
| Unsalted butter                 | 40g      |      5% | 2. Cook sous vide in 54 degC bath,               |
|                                 |          |         | about 1 1/4 h.                                   |
|                                 |          |         | 3. Sear surface with blowtorch                   |
|                                 |          |         | yields: Rib Eye, cooked                          |
|---------------------------------+----------+---------+--------------------------------------------------|
| Shallots, finely minced         | 50g      |      6% | 1. Sweat until shallots are tender but not brown |
| Fennel, finely minced           | 25g      |      3% |                                                  |
| Neutral oil                     | 12.5g    |    1.5% | yields: Shallot Mixture                          |
|---------------------------------+----------+---------+--------------------------------------------------|
| Pickled Cherry Brine            | 150g     |     19% | 1. Add to Shallot Mixture                        |
| Red Wine Vinegar                | 50g      |      6% | 2. Reduce to 100g                                |
| Red Wine (Pinot Noir)           | 40g      |      6% |                                                  |
| Quatre epices                   | 0.5g     |   0.05% | yields: Cherry Marmalade                         |
| Black Peppercorns, crushed      | 0.4g     |   0.05% |                                                  |
| Juniper berries, finely ground  | 0.4g     |   0.05% |                                                  |
| Coriander seeds, finely ground  | 0.15g    |   0.02% |                                                  |
|---------------------------------+----------+---------+--------------------------------------------------|
| Pickled cherries, finely minced | 100g     |   12.5% | 1. Whisk into marmalade                          |
| Grain mustard                   | 40g      |      5% |                                                  |
| Morcello cherry puree           | 35g      |    4.5% | yields: Cherry Mustard Marmalead sauce           |
| Pressure-cooked mustard seeds   | 8g       |      1% |                                                  |
|---------------------------------+----------+---------+--------------------------------------------------|
| Porcini (fresh)                 | 100g     |   12.5% | 1. Slice Porcini very thinly                     |
| Nuetral Oil                     | As need  |         | 2. Quickly sautee until golden                   |
|                                 |          |         | yields: Sateed Porcini                           |
|---------------------------------+----------+---------+--------------------------------------------------|
| Salt                            | taste    |         | 1. Slice meat to desired thickness               |
|                                 |          |         | 2. Season meat, marmalade, and mushrooms,        |
|                                 |          |         | and arrange on plate.                            |
|---------------------------------+----------+---------+--------------------------------------------------|

Tips and Technique:
Flaky sea salt is a great way to finish a cooked piece of meat or fish.  It adds crunchy bursts of saltiness. The only problem is that the salt tends to dissolve into the natural juices by the time the dish reaches the table.  Herve This came up with a solution: toss the salt crystals with oil or fat.  A thin layer of oil then seperates the flakes from the cooking juices and prevents the salt from dissolving.

 
**** Json
{ 
  id: MsgId,
  type: "recipe"
  author: FeedId,
  content: {
    name: string,
    timestamp: number,
    tasks:[task_id,]
    description: textfield,
    notes: string
  }
}


*** Tasks
- steps
- duration
- ingredients
- equipment
- media
- yields

- necessary_conditions
**** JSON
{ 
  id: task_id,
  type: "task"
  author: FeedId,
  contents: {
    name: string,
    items: [{item: item-id, qty: number, unit: unit-id }, ...]
    yields: [{item: item-id, qty: number, unit: unit-id }, ...]
    steps: [string, ...]
    notes: string
    equipment: [{item: item-id, qty: number, unit: unit-id }, ...]
    duration: number (ms)
}

*** Suppliers
- contact_info
- order_requirements 
  email, api, minimum costs, net 30, etc.
- price_list 
  item, price, qty, unit (purchase unit may be different then other unit, i.e. box of 8 each)
  
*** People (Contacts?)
- name
? access
- primary_location
- skillset
- contact_info
*** Group (Organization?)
- name
- access
- people_list
- location
*** Location
- name
- lat_long
- address
- sublocations
- tags
- timezone
*** Events
- location (contains timezone, etc.)
- datetime
- participants (group, or list of people)
- duration (calculated from tasks?)
? reoccurring
? frequency
? completion
*** Lot Tracking (completion of an event/task)
- task/recipe/product
- batch
- scan {timestamp, person, tracking number}
*** Payment
- transaction
- person
- payment method (cash, credit card, paypal, bitcoin, etc.)
- tax
- services (shipping, coupons, etc.)
*** Orders
- type [Purchase, Requisition, Transfer, Sales, Physical Inventory?, Merchandise Arrival?]
- location
- supplier
- purchaser
- payment
- item_list (item, qty, unit, price, options)
+ item_total
- shipping_costs
- tax
- signatures
- order_date
- fulfillment_date
*** Purchase_Orders <-- make a part of generic Orders?
- location
- supplier
- purchaser
- signature
- payment_method
- purchase_list (item, qty, unit, price)
- item_total
- tax
- shipping_cost
+ total_cost
*** Requisition_Order  <-- make a part of generic Orders?
- item_list
- created_by
- creation_date
- need_by
*** Chart of Accounts
-name
-department
-account_number 
*** Transactions
- debit_account
- credit_account
- amount
- type [purchase, sale, transfer, payroll, equity disbursement, loan payment, spoilage/loss, etc.] 
- date_time
- memo
- currency_type
*** Products
- qty
- unit
- item
? packaging
? price
? description
? media
? options (sizes, colors, etc.)

*** Sales_Order  <-- make a part of generic Orders?
- location (POS terminal, etc.)
- customer
- product_list (item, qty, unit, options, cost)
+ subtotal
+ sales_tax
+ shipping_costs
- payment_method
*** Physical_Inventory  <-- make a part of generic Orders?
- location
- qoh (item, qty, unit) a.k.a quantity on hand, simpler to use item_list?
- par_levels (bin, item, min_qty, max_qty)
*** Merchandise_Arrival  <-- make a part of generic Orders?
- location
- item_list (item, qty, unit)
- reciever
*** Schedule  <-- role into Events?
- location
- person
- task (event data and process)
- assigned_to (group or person)
- task/recipe
- event
- completing_date
*** Pattern Language
****  Name 
- single word or short phrase that refers to the pattern. This allows for rapid association and retrieval.
**** Problem 
- definition of a problem, including its intent or a desired outcome, and symptoms that would indicate that this problem exists.
**** Context 
– preconditions which must exist in order for that problem to occur; this is often a situation. When forces conflict, the resolutions of those conflicts is often implied by the context.
**** Forces 
– description of forces or constraints and how they interact. Some of the forces may be contradictory. For example: being thorough often conflicts with time or money constraints.
**** Solution 
– instructions, possibly including variants. The solution may include pictures, diagrams, prose, or other media.
**** Examples
– sample applications and solutions, analogies, visual examples, and known uses can be especially helpful, help user understand the context
**** Resulting Context 
– result after the pattern has been applied, including postconditions and side effects. It might also include new problems that might result from solving the original problem.
**** Rationale 
– the thought processes that would go into selecting this pattern, The rationale includes an explanation of why this pattern works, how forces and constraints are resolved to construct a desired outcome.
**** Related Patterns 
– differences and relationships with other patterns, possibly predecessor, antecedents, or alternatives that solve similar problems.

*** Needs
- Search query of Products/Services that one needs

* Contracts
** Legal Domain Specific Language 
- https://catala-lang.org/
* Tutorials
** Re-learn pop-up tutorials for re-frame
- https://github.com/oliyh/re-learn
* Cryptography in Clojure
** Buddy.core
- https://cljdoc.org/d/buddy/buddy-core/1.10.1/doc/user-guide

* NPM dependencies
** Adding
#+BEGIN_SRC sh
npm install the-thing
#+END_SRC
** Removing
#+BEGIN_SRC sh
npm uninstall the-thing
#+END_SRC

* CSS
** Available (in Hiccup notation)
#+BEGIN_SRC clojurescript

[:div.arrow_box "text for arrow box"]
[:div.blue-panel "text for blue panel"]
[:div.white-panel "text for white panel"]
[:div.help-text "help text"]
[:div#task
 [:div.steps-indicator
  [:div.connector]
  [:div.connector.complete]
  [:ol.steps
   [:li.complete [:strong "completed"] " step"]
   [:li.active "not complete"]
   [:li.active "not complete"]
   [:li.inactive "inactive"]
   [:li.warning "warning"]
   [:li.active "last one"]]]]

#+END_SRC

* Yield Management
- Recipes yield desireable products and waste.  
- Waste can eventually be used as an ingredient for another recipe.
- Locations and equipment yield in a similar way, but the consumable product is time itself, ie a room can be rented for a duration, but if it is not used then that past time period does not remain in inventory. Scheduling is how this resource is managed.

* decentangle
- decentralized entangle 
